# print("Hello\nWorld")
# print("\"!@#$%^&*()'")
# print("\"C:\\Download\\'hello'.py\"")
# print('print("Hello\\nWorld")')
# f = float(input())
# print(f)
# a, b = input().split()
# print(b,a)
# a, b = input().split(':')
# print(a, b, sep=':')
# y, m, d = input().split('.')
# print(d,m,y,sep='-')
# a,b=input().split('-')
# print(a,b,sep='')
# s = input()
# print(s[0:2],s[2:4],s[4:6])
a, b, c = input().split(':')
print(b)